# Para mudar string faça: Int(nome)
idade = input("Digite sua idade :")
idade_de_parente = input("Você pode informar a idade de um parente:")
nome_do_usuario = input("Digite seu nome :")
print(int(idade) * int(idade_de_parente))
print(nome_do_usuario)
